### PR TITLE
Fix for missing environment variables

### PR DESCRIPTION
**Pull request by qqdanielqq**
Adds a missing clause for Confex style application environment variables

### CODE REVIEW

**Comment by Thau** [comment]
I won't block this because it looks well done, but I'm also not sure if we really need this, seeing that we have function support on terms, and `fn -> System.get_env("TOPIC_NAMES") end` it's just some more characters in exchange of less code in the library.

**Comment by qqdanielqq** [comment]
The way that Event Serializer is receiving topics currently in master is throwing an error even with the function support on the terms.

**Comment by luizvarela** [comment]
@qqdanielqq Let's update the CHANGELOG

**Comment by luizvarela** [comment]
We also need to update the version number

**Review by luizvarela — APPROVED** [review]

**Pull request merged**
